### PR TITLE
Adds information to the Perth page

### PR DESCRIPTION
**Pull request by philippbayer**
PR for discussion, what is missing:
- correct link for registration
- blurbs & pictures (if available) for all speakers
- blurbs for all minor electives
- accommodation text
- exact times for the time-plan

### CODE REVIEW

**Comment by katieannemills** [comment]
Looking good so far! I don't see a change to the reg link from your first bullet, nor are there any pictures in this PR per your second bullet; I assume they're coming soon. Would you like me to merge this as is, or shall I wait for further commits? Happy to help, thanks for the PR!

**Comment by philippbayer** [comment]
Thank you :) I haven't changed the registration link yet because I don't have the new one, I'm waiting for that. I've also contacted the others for blurbs etc., for now I wouldn't merge the PR, I'll add more commits over the next few days, I think I'll comment again once it's done

**Comment by arohl** [comment]
1. The page hasn't changed - does this mean that Bill hasn't merged yet?
2. I can answer the accomodation question - there isn't any so please delete that section
3. I think the meet our speakers section needs to change as we aren't having KeyStory speakers or the You section - I guess this is where we will list the presenters of the courses and the helpers - does this work for you Bill?
4. Our event won't be free - we will be charging $50 per person to cover the full three days which needs to be in the preamble
5. Philipp - what does exact times for the time-plan mean? I though we had precise timing in the draft.
6. Philipp - Can you set up the WA registration - I think the Global one uses Google Forms - we should use the same for ours - I think you can see the Melbourne one at https://docs.google.com/a/yuandraismiraldi.net/forms/d/1QPsCM2Cx50FreMyoKkYEsOiSC3XFhT21KuoXM5rghHA/edit?usp=sharing and we should use this as a starting point

Finally I hope that this can go live (i.e. be advertised far and wide in WA) by Friday...

**Comment by katieannemills** [comment]
Hi @arohl - nope, I haven't merged yet since @philippbayer mentioned he still had some content coming shortly. Everything else sounds good to me!

**Comment by philippbayer** [comment]
Hi @arohl - I'll set up the Google signup page and add the the link to this site, then we can merge this PR. Here's the link so far, still editing: https://docs.google.com/forms/d/1H8gMK0s1-oGRJaDGL7BIVDPVG-NwqqX4Y-uVgW_CCtk/edit#
1. Will delete accommodation
2. For now I'll just put the names in that I have - we'll need short self-descriptions from everybody eventually
3. Will add $50 to preamble, it's already in the form
4. No worries, I'll add the times to the table

Will definitely have this done today

**Comment by philippbayer** [comment]
I think it can be merged now! I've added the new Google Form link and included various minor fixes.

I'll probably open another pull request in a month or so once I got all the text for the blurbs, the  instructor self-descriptions and sponsors.

**Comment by katieannemills** [comment]
Thanks, @philippbayer + @arohl - had to touch up some merge conflicts around the registration link, so do please have a look and make sure everything came out the way you hoped.

**Pull request merged**
