### PR TITLE
Update 2016-02-01-brisbane.html

### PR DESCRIPTION
**Pull request by weaverbel**
adding locations and links to workshops

### CODE REVIEW

**Comment by DamienIrving** [comment]
@tjdett This pull request causes no problem when I do `jekyll serve --future` on my own machine (and hence I merged it), however GitHub then sent me an email that simply says "Page build failed" with no further details (and points me to [this page](https://help.github.com/articles/troubleshooting-github-pages-build-failures/)). Have you come across this before?

**Comment by katieannemills** [comment]
Page builds just randomly fail once in a while - did you try pushing a trivial change to trigger another rebuild?

**Comment by weaverbel** [comment]
We are good now – changes are showing.
Thanks Bill
Belinda

**Comment by katieannemills** [comment]
Yep - probably fixed itself when Ivan triggered a rebuild. If #59 works locally for you it should be good to merge.

**Comment by weaverbel** [comment]
OK, have alerted Sam who usually checks.
Thanks
Belinda

**Pull request merged**
