### PR TITLE
Removes registration link. Adds two instructor pics + bios.

### PR DESCRIPTION
**Pull request by philippbayer**
Registrations are now closed so I removed the link to the forms - also adds picture + blurb for two instructors

### CODE REVIEW

**Comment by katieannemills** [comment]
thanks, @philippbayer!

**Comment by DamienIrving** [comment]
@philippbayer Do you want me to add you as a collaborator on this repo so you can make simple changes to the Perth page without needing to make a pull request?

**Comment by philippbayer** [comment]
Hi @DamienIrving,

that would be nice! I promise I won't break the place

**Comment by DamienIrving** [comment]
@philippbayer - done :smile:

**Comment by philippbayer** [comment]
Thank you very much :neckbeard:

**Pull request merged**
