### PR TITLE
Closed registration option for Dunedin event

### PR DESCRIPTION
**Pull request by mikblack**
Registration and survey links removed, and replaced with mailto option.

### CODE REVIEW

**Comment by DamienIrving** [comment]
@mikblack I can add someone from Dunedin as a collaborator on this repo if you'd like to be able to make simple changes to the Dunedin page without needing to submit a pull request?

**Comment by mikblack** [comment]
@DamienIrving if you could add me as a collaborator, that would be great - thanks.

**Comment by DamienIrving** [comment]
@mikblack Done :-)

**Comment by mikblack** [comment]
@DamienIrving Cool - thanks.  :)

**Pull request merged**
